<a href="https://colab.research.google.com/github/anishchapagain/Deep-Learning/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Principal component analysis (PCA) is a statistical technique that reduces the number of dimensions in a dataset while preserving as much information as possible.

### In machine learning, "dimensionality reduction" refers to the process of decreasing the number of features (variables) in a dataset while still preserving the most important information

In [1]:
import pandas as pd

### Random Value

In [2]:
import numpy as np

# Set a seed for reproducibility
np.random.seed(42)

# Number of records
n_records = 100

# Create a list of towns in Nepal
towns = ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar', 'Bharatpur']

# Generate data
data = {
    'town': np.random.choice(towns, n_records),
    'area': np.random.randint(50, 500, n_records),  # Area in sq meters
    'bathroom': np.random.randint(1, 5, n_records),
    'schools_nearby': np.random.randint(0, 3, n_records),
    'price': np.random.randint(500000, 10000000, n_records)  # Price in NPR
}

# Create a pandas DataFrame
df = pd.DataFrame(data)

# Display the first few rows
print(df.head())


         town  area  bathroom  schools_nearby    price
0  Biratnagar    77         4               0  1605534
1   Bharatpur   184         1               0  4853127
2    Lalitpur   250         4               1  7815360
3   Bharatpur   377         1               0  8573461
4   Bharatpur   317         2               1   998863


In [3]:
df.town.value_counts()

,count
town,
Biratnagar,26
Pokhara,21
Bharatpur,19
Kathmandu,18
Lalitpur,16


In [4]:
df.describe(include='all')

,town,area,bathroom,schools_nearby,price
count,100,100.000000,100.000000,100.000000,1.000000e+02
unique,5,NaN,NaN,NaN,NaN
top,Biratnagar,NaN,NaN,NaN,NaN
freq,26,NaN,NaN,NaN,NaN
mean,NaN,268.420000,2.640000,0.900000,5.015216e+06
std,NaN,126.338904,1.132798,0.822659,2.789572e+06
min,NaN,54.000000,1.000000,0.000000,6.188340e+05
25%,NaN,168.750000,2.000000,0.000000,2.619672e+06
50%,NaN,272.500000,3.000000,1.000000,4.772226e+06
75%,NaN,376.250000,4.000000,2.000000,7.317376e+06


In [36]:
df.shape

(100, 5)

In [5]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [6]:
# Select numerical features for PCA
features = ['area', 'bathroom', 'schools_nearby', 'price']
x = df.loc[:, features].values

In [10]:
x[3:10]

array([[    377,       1,       0, 8573461],
       [    317,       2,       1,  998863],
       [    467,       1,       0, 9256262],
       [     82,       2,       0, 3176188],
       [     97,       4,       2, 3795990],
       [    456,       4,       2, 8282937],
       [    111,       2,       0, 7026818]])

In [ ]:
# Scale the features using StandardScaler.
# This transforms the data to have zero mean and unit variance, which is often beneficial for PCA.

x = StandardScaler().fit_transform(x)

In [12]:
x

array([[-1.52276402,  1.20661485, -1.099525  , -1.22845368],
       [-0.671569  , -1.45503555, -1.099525  , -0.05839816],
       [-0.14653282,  1.20661485,  0.12216944,  1.00884675],
       [ 0.86376407, -1.45503555, -1.099525  ,  1.28197834],
       [ 0.38645845, -0.56781875,  0.12216944, -1.44702748],
       [ 1.57972249, -1.45503555, -1.099525  ,  1.52798056],
       [-1.48298856, -0.56781875, -1.099525  , -0.66257231],
       [-1.36366215,  1.20661485,  1.34386389, -0.43926761],
       [ 1.49221646,  1.20661485,  1.34386389,  1.17730722],
       [-1.25229084, -0.56781875, -1.099525  ,  0.72474775],
       [-0.02720642,  0.31939805, -1.099525  ,  1.68269548],
       [ 0.58533579, -0.56781875,  1.34386389,  0.35177175],
       [-0.95795238,  0.31939805,  1.34386389,  0.71956758],
       [-0.37723054, -1.45503555,  1.34386389,  0.57083806],
       [ 1.11832706, -1.45503555,  0.12216944,  0.73525002],
       [-0.04311661, -1.45503555, -1.099525  , -0.6543481 ],
       [-1.46707837,  1.

In [37]:
# Apply PCA with 2 components

pca = PCA(n_components=2) # desired only 2 components
# pca = PCA(0.95)
principalComponents = pca.fit_transform(x)

In [38]:
principalComponents.shape

(100, 2)

In [40]:
pca.explained_variance_ratio_ # first column: 29% , second 26

array([0.29668118, 0.26996967])

In [14]:
principalComponents

array([[ 1.25776494, -0.91091843],
       [-0.92905869, -1.4002862 ],
       [ 0.36328237,  1.39803852],
       [-2.27695734,  0.01972535],
       [ 0.10988552, -1.18456121],
       [-2.76667549,  0.41889363],
       [ 0.17285258, -1.55415465],
       [ 2.26617465,  0.32216526],
       [ 0.08004685,  2.35522861],
       [-0.46405716, -0.51789409],
       [-1.07099409,  1.0620446 ],
       [ 0.0331576 ,  0.44441837],
       [ 1.18755017,  0.73143859],
       [ 0.0624548 , -0.23503392],
       [-1.52564977,  0.03894571],
       [-1.06154623, -1.6132611 ],
       [ 1.59260325,  1.67454193],
       [-1.90355031, -1.39829079],
       [ 0.45507583, -0.26313013],
       [ 0.07014128, -1.46306466],
       [ 0.01365402, -0.32909923],
       [ 0.23189981, -0.61111508],
       [ 0.29893213, -0.43938757],
       [ 1.95094767, -1.49727879],
       [-0.31319754, -0.38528772],
       [-0.90310034, -2.15421499],
       [ 0.02643224,  0.87920577],
       [-1.43376231, -0.12925497],
       [-1.10360002,

In [15]:
# Create a new DataFrame with the principal components

principalDf = pd.DataFrame(data = principalComponents, columns = ['principal_componentA', 'principal_componentB'])

# Concatenate with the original DataFrame
finalDf = pd.concat([principalDf, df[['town']]], axis = 1)

print(finalDf.head())

   principal_componentA  principal_componentB        town
0              1.257765             -0.910918  Biratnagar
1             -0.929059             -1.400286   Bharatpur
2              0.363282              1.398039    Lalitpur
3             -2.276957              0.019725   Bharatpur
4              0.109886             -1.184561   Bharatpur


In [16]:
features

['area', 'bathroom', 'schools_nearby', 'price']

In [17]:
pca.explained_variance_ratio_ #

array([0.29668118, 0.26996967])

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [31]:
X_train, X_test, y_train, y_test = train_test_split(x, df['price'], test_size=0.2, random_state=42)

In [32]:
logistic = LogisticRegression()
logistic.fit(X_train, y_train)

LogisticRegression()

In [33]:
logistic.score(X_train, y_train)

0.575

In [34]:
logistic.score(X_test, y_test)

0.0

## RandomForest

In [18]:
# Based on the provided code, the features used for PCA are:
# 'area', 'bathroom', 'schools_nearby', and 'price'

# To determine which features are most important for predicting something (like 'price' in this case),
# I will typically use feature importance techniques like those available in various machine-learning models
# (e.g. Random Forest, Gradient Boosting, etc.).

# PCA is a dimensionality reduction technique and does not inherently reveal
# feature importance in relation to a target variable.  The principal components are linear combinations of the original features.


# Example using RandomForestRegressor to illustrate feature importance:

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [19]:
# Assuming 'price' to be predicted

X = df[['area', 'bathroom', 'schools_nearby']] # Features (excluding town since it's categorical)
y = df['price'] # Target variable

In [20]:
# Split data into training and testing sets (80/21 with 42 randomness)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
# Initialize and train a RandomForestRegressor

model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [22]:
# Get feature importances
importances = model.feature_importances_
print(importances)

[0.6406645  0.22020712 0.13912838]


In [23]:
importances.sum()

0.9999999999999999

In [25]:
importances.max()

0.6406645010273145

In [26]:
# Print feature importances with feature names

for feature, importance in zip(X.columns, importances):
    print(f"{feature}: {importance}")

area: 0.6406645010273145
bathroom: 0.22020712281124935
schools_nearby: 0.13912837616143603


## Questions?