# Pytorch - Tensors, Dot Product and Matrix Multiplication

## PyTorch Tensors: Properties and Operations 
1. [Official Tutorial - Tensors](https://docs.pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html) <br>
2. [Official Tutorial - Deep Learning with PyTorch](https://docs.pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html) <br>
3. [Sebastian Raschka - PyTorch in 1Hour](https://sebastianraschka.com/teaching/pytorch-1h/)

PyTorch tensors are similar to NumPy arrays but can run on GPUs for accelerated computing. Let's explore some of their fundamental properties and operations.

In [35]:
import torch

### 1. Tensor Properties: ndim, shape, size, len
#### 1-D Tensor (Vector)

In [36]:
vector = torch.tensor([1, 2, 3, 4])

print(f"\nVector: {vector}")
print(f"Number of dimensions (ndim): {vector.ndim}") # Number of dimensions
print(f"Shape: {vector.shape}") # Size of each dimension
print(f"Total number of elements (size): {vector.size()}") # Total elements
print(f"Length (len): {len(vector)}") # Length of the first dimension


Vector: tensor([1, 2, 3, 4])
Number of dimensions (ndim): 1
Shape: torch.Size([4])
Total number of elements (size): torch.Size([4])
Length (len): 4


#### 2-D Tensor (Matrix)

In [37]:
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])
print(f"\nMatrix:\n{matrix}")
print(f"Number of dimensions (ndim): {matrix.ndim}")
print(f"Shape: {matrix.shape}")
print(f"Total number of elements (size): {matrix.size()}")
print(f"Length (len): {len(matrix)}")


Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions (ndim): 2
Shape: torch.Size([2, 3])
Total number of elements (size): torch.Size([2, 3])
Length (len): 2


#### 3-D Tensor

In [38]:
tensor_3d = torch.tensor([[[1, 2],
                           [3, 4]],
                          [[5, 6],
                           [7, 8]]])
                           
print(f"\n3D Tensor:\n{tensor_3d}")
print(f"Number of dimensions (ndim): {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")
print(f"Total number of elements (size): {tensor_3d.size()}")
print(f"Length (len): {len(tensor_3d)}")


3D Tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Number of dimensions (ndim): 3
Shape: torch.Size([2, 2, 2])
Total number of elements (size): torch.Size([2, 2, 2])
Length (len): 2


## Data Types (`dtypes`)

PyTorch supports various data types for tensors, which determine how the numbers are stored in memory. Common dtypes include `torch.float32` (or `torch.float`), `torch.float64` (or `torch.double`), `torch.int32` (or `torch.int`), `torch.int64` (or `torch.long`), and `torch.bool`.

In [39]:
# Default float dtype is torch.float32
tensor_float = torch.tensor([1.0, 2.0, 3.0])
print(f"\nFloat Tensor: {tensor_float}, Dtype: {tensor_float.dtype}")

# Integer tensor (default is torch.int64 for integers)
tensor_int = torch.tensor([1, 2, 3])
print(f"Integer Tensor: {tensor_int}, Dtype: {tensor_int.dtype}")

# Explicitly define dtype
tensor_float64 = torch.tensor([1.0, 2.0], dtype=torch.float64)
print(f"Float64 Tensor: {tensor_float64}, Dtype: {tensor_float64.dtype}")

tensor_int32 = torch.tensor([10, 20], dtype=torch.int32)
print(f"Int32 Tensor: {tensor_int32}, Dtype: {tensor_int32.dtype}")

# Type casting
tensor_to_cast = torch.tensor([1.5, 2.8, 3.1])
print(f"\nOriginal Tensor: {tensor_to_cast}, Dtype: {tensor_to_cast.dtype}")

tensor_casted_int = tensor_to_cast.long() # Cast to long (int64)
print(f"Casted to Long: {tensor_casted_int}, Dtype: {tensor_casted_int.dtype}")

tensor_casted_float = tensor_int32.float() # Cast int32 to float32
print(f"Casted to Float: {tensor_casted_float}, Dtype: {tensor_casted_float.dtype}")


Float Tensor: tensor([1., 2., 3.]), Dtype: torch.float32
Integer Tensor: tensor([1, 2, 3]), Dtype: torch.int64
Float64 Tensor: tensor([1., 2.], dtype=torch.float64), Dtype: torch.float64
Int32 Tensor: tensor([10, 20], dtype=torch.int32), Dtype: torch.int32

Original Tensor: tensor([1.5000, 2.8000, 3.1000]), Dtype: torch.float32
Casted to Long: tensor([1, 2, 3]), Dtype: torch.int64
Casted to Float: tensor([10., 20.]), Dtype: torch.float32


## Element-wise Addition (`torch.add` or `+` operator)

Element-wise addition performs addition on corresponding elements of two tensors. The tensors must have compatible shapes (broadcasting rules apply).

In [40]:
tensor_a = torch.tensor([[1, 2],
                         [3, 4]])
tensor_b = torch.tensor([[5, 6],
                         [7, 8]])

print(f"Tensor A:\n{tensor_a}")
print(f"Tensor B:\n{tensor_b}")

# Element-wise addition using torch.add
add_result_func = torch.add(tensor_a, tensor_b)
print(f"\nAddition using torch.add:\n{add_result_func}")

# Element-wise addition using the + operator
add_result_op = tensor_a + tensor_b
print(f"\nAddition using + operator:\n{add_result_op}")

# Example with broadcasting
tensor_scalar = torch.tensor(10)
broadcast_add = tensor_a + tensor_scalar
print(f"\nTensor A + Scalar (Broadcasting):\n{broadcast_add}")

Tensor A:
tensor([[1, 2],
        [3, 4]])
Tensor B:
tensor([[5, 6],
        [7, 8]])

Addition using torch.add:
tensor([[ 6,  8],
        [10, 12]])

Addition using + operator:
tensor([[ 6,  8],
        [10, 12]])

Tensor A + Scalar (Broadcasting):
tensor([[11, 12],
        [13, 14]])


## Concatenation (`torch.cat`)

`torch.cat` is used to concatenate (join) a sequence of tensors along a given dimension. All tensors must either have the same shape (except in the concatenating dimension) or be empty.

In [41]:
tensor1 = torch.tensor([[1, 2],
                        [3, 4]])
tensor2 = torch.tensor([[5, 6],
                        [7, 8]])

print(f"Tensor 1:\n{tensor1}")
print(f"Tensor 2:\n{tensor2}")

# Concatenate along dimension 0 (rows)
cat_dim0 = torch.cat((tensor1, tensor2), dim=0)
print(f"\nConcatenated along dim=0 (rows):\n{cat_dim0}")

# Concatenate along dimension 1 (columns)
cat_dim1 = torch.cat((tensor1, tensor2), dim=1)
print(f"\nConcatenated along dim=1 (columns):\n{cat_dim1}")

# Example with 1D tensors
vec1 = torch.tensor([1, 2, 3])
vec2 = torch.tensor([4, 5, 6])
cat_vec = torch.cat((vec1, vec2), dim=0)
print(f"\nConcatenated 1D tensors: {cat_vec}")

Tensor 1:
tensor([[1, 2],
        [3, 4]])
Tensor 2:
tensor([[5, 6],
        [7, 8]])

Concatenated along dim=0 (rows):
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

Concatenated along dim=1 (columns):
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

Concatenated 1D tensors: tensor([1, 2, 3, 4, 5, 6])


## `torch.dot`: Dot Product of 1-D Tensors

`torch.dot` is used to compute the dot product of two 1-D tensors (vectors). The result is a scalar value.

In [48]:
import torch

# Create two 1-D tensors (vectors)
vector_a = torch.tensor([1, 2, 3])
vector_b = torch.tensor([4, 5, 6])

# Compute the dot product using torch.dot
# Result = (1*4) + (2*5) + (3*6) = 4 + 10 + 18 = 32
dot_product = torch.dot(vector_a, vector_b)

print(f"Vector A: {vector_a}")
print(f"Vector B: {vector_b}")
print(f"Dot Product: {dot_product}")

Vector A: tensor([1, 2, 3])
Vector B: tensor([4, 5, 6])
Dot Product: 32


## `torch.matmul`: Matrix Multiplication

`torch.matmul` is a more general function for matrix multiplication. It can handle tensors of different dimensions.

### 1. Matrix-Vector Multiplication

In [49]:
# Create a matrix and a vector
matrix = torch.tensor([[1, 2],
                       [3, 4]])
vector = torch.tensor([5, 6])

# Perform matrix-vector multiplication
# Result[0] = (1*5) + (2*6) = 5 + 12 = 17
# Result[1] = (3*5) + (4*6) = 15 + 24 = 39
result_mv = torch.matmul(matrix, vector)

print(f"Matrix: {matrix}")
print(f"Vector: {vector}")
print(f"Matrix-Vector Multiplication Result: {result_mv}")

Matrix: tensor([[1, 2],
        [3, 4]])
Vector: tensor([5, 6])
Matrix-Vector Multiplication Result: tensor([17, 39])


### 2. Matrix-Matrix Multiplication

In [50]:
# Create two matrices
matrix_a = torch.tensor([[1, 2],
                         [3, 4]])
matrix_b = torch.tensor([[5, 6],
                         [7, 8]])

# Perform matrix-matrix multiplication
# Result[0,0] = (1*5) + (2*7) = 5 + 14 = 19
# Result[0,1] = (1*6) + (2*8) = 6 + 16 = 22
# Result[1,0] = (3*5) + (4*7) = 15 + 28 = 43
# Result[1,1] = (3*6) + (4*8) = 18 + 32 = 50
result_mm = torch.matmul(matrix_a, matrix_b)

print(f"Matrix A:{matrix_a}")
print(f"Matrix B:{matrix_b}")
print(f"Matrix-Matrix Multiplication Result:{result_mm}")

Matrix A:tensor([[1, 2],
        [3, 4]])
Matrix B:tensor([[5, 6],
        [7, 8]])
Matrix-Matrix Multiplication Result:tensor([[19, 22],
        [43, 50]])


## `torch.dot` vs `torch.matmul` for 1-D Tensors

When used with two 1-D tensors, `torch.matmul` also computes the dot product. However, there's a subtle difference in the output:
- `torch.dot` returns a **scalar** (a single number).
- `torch.matmul` returns a **0-D tensor** (a tensor containing a single number).

In [51]:
# Using the same vectors from the first example
vector_a = torch.tensor([1, 2, 3])
vector_b = torch.tensor([4, 5, 6])

# Dot product with torch.dot
dot_result = torch.dot(vector_a, vector_b)

# Dot product with torch.matmul
matmul_result = torch.matmul(vector_a, vector_b)

print(f"Result from torch.dot: {dot_result} (Type: {type(dot_result)})")
print(f"Result from torch.matmul: {matmul_result} (Type: {type(matmul_result)})")

Result from torch.dot: 32 (Type: <class 'torch.Tensor'>)
Result from torch.matmul: 32 (Type: <class 'torch.Tensor'>)


## Transposing a Matrix (`.T` or `transpose()`)

Transposing a matrix means flipping it over its diagonal, i.e., rows become columns and columns become rows. In PyTorch, you can use the `.T` attribute or the `transpose()` method.

In [52]:
# Original matrix
matrix_orig = torch.tensor([[1, 2, 3],
                            [4, 5, 6]])
print(f"Original Matrix:\n{matrix_orig}")
print(f"Shape of Original Matrix: {matrix_orig.shape}")

# Transpose using .T
matrix_transposed_T = matrix_orig.T
print(f"\nTransposed Matrix (.T):\n{matrix_transposed_T}")
print(f"Shape of Transposed Matrix (.T): {matrix_transposed_T.shape}")

# Transpose using transpose(dim0, dim1)
# For a 2D tensor, dim0=0 (rows), dim1=1 (columns)
matrix_transposed_func = torch.transpose(matrix_orig, 0, 1)
print(f"\nTransposed Matrix (transpose(0,1)):\n{matrix_transposed_func}")
print(f"Shape of Transposed Matrix (transpose(0,1)): {matrix_transposed_func.shape}")

Original Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape of Original Matrix: torch.Size([2, 3])

Transposed Matrix (.T):
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Shape of Transposed Matrix (.T): torch.Size([3, 2])

Transposed Matrix (transpose(0,1)):
tensor([[1, 4],
        [2, 5],
        [3, 6]])
Shape of Transposed Matrix (transpose(0,1)): torch.Size([3, 2])


# Neural Networks using PyTorch

In [1]:
import torch.nn as nn

## `state_dict` and `parameters` (for Neural Networks)

When working with neural networks in PyTorch, `state_dict` and `parameters` are crucial for saving, loading, and inspecting the model's learnable weights and biases.

- `state_dict()`: Returns a dictionary containing a whole state of the module. This includes all parameters and persistent buffers.
- `parameters()`: Returns an iterator over module parameters. These are the tensors that are updated during training.

In [2]:
# Creating a simple neural network
class SimpleNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = nn.Linear(10, 5) # 10 input features, 5 output features
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(5, 1)  # 5 input features, 1 output feature

    def forward(self, x):
        x = self.linear1(x)
        x = self.relu(x)
        x = self.linear2(x)
        return x

model = SimpleNN()

print("\nModel's state_dict:")
for param_tensor, value in model.state_dict().items():
    print(f"{param_tensor}\t{value.size()}")

print("\nModel's learnable parameters:")
for name, param in model.named_parameters():
    if param.requires_grad:
        print(f"{name}\t{param.size()}")


Model's state_dict:
linear1.weight	torch.Size([5, 10])
linear1.bias	torch.Size([5])
linear2.weight	torch.Size([1, 5])
linear2.bias	torch.Size([1])

Model's learnable parameters:
linear1.weight	torch.Size([5, 10])
linear1.bias	torch.Size([5])
linear2.weight	torch.Size([1, 5])
linear2.bias	torch.Size([1])


In [3]:
# Display available variables and their types/values
print("Available variables:")
vars_to_show = {
    'model': model,
    'name': name,
    'param': param,
    'param_tensor': param_tensor,
    'value': value
}
for k, v in vars_to_show.items():
    try:
        print(f"{k}: type={type(v)}, value={v}")
    except Exception:
        print(f"{k}: type={type(v)}, value=<<unprintable>>")

# Show model state_dict keys and shapes
print("\nModel's state_dict keys and shapes:")
for k, v in model.state_dict().items():
    print(f"{k}\t{v.size()}")

# Print model's learnable parameters (as requested)
print("\nModel's learnable parameters:")
for name, param in model.named_parameters():
    if param.requires_grad:
        print(f"{name}\t{param.size()}")

Available variables:
model: type=<class '__main__.SimpleNN'>, value=SimpleNN(
  (linear1): Linear(in_features=10, out_features=5, bias=True)
  (relu): ReLU()
  (linear2): Linear(in_features=5, out_features=1, bias=True)
)
name: type=<class 'str'>, value=linear2.bias
param: type=<class 'torch.nn.parameter.Parameter'>, value=Parameter containing:
tensor([-0.1578], requires_grad=True)
param_tensor: type=<class 'str'>, value=linear2.bias
value: type=<class 'torch.Tensor'>, value=tensor([-0.1578])

Model's state_dict keys and shapes:
linear1.weight	torch.Size([5, 10])
linear1.bias	torch.Size([5])
linear2.weight	torch.Size([1, 5])
linear2.bias	torch.Size([1])

Model's learnable parameters:
linear1.weight	torch.Size([5, 10])
linear1.bias	torch.Size([5])
linear2.weight	torch.Size([1, 5])
linear2.bias	torch.Size([1])


## Conclusion

### In this notebook, we viewed and executed some of the core PyTorch tensor's related features. Also, dig a bit inside how the Neural Network is defined and checked their core params and objects.