<a href="https://colab.research.google.com/github/anishchapagain/Deep-Learning/blob/main/torch_nn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch for Deep Learning Models

Linear Regression Model Training in PyTorch

In [2]:
import torch

Input Data: tensor

In [7]:
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
print(X)

tensor([[1.],
        [2.],
        [3.],
        [4.]])


Expected Output: y = 5x+1<br><b>Learning_weight:5, Learning_bias:1</b><br>
example: x=1, y=5*1+1 = 6

In [21]:
y = torch.tensor([[6.0], [11.0], [15.0], [21.0]]) # 21 = 5*4+1
print(y)

tensor([[ 6.],
        [11.],
        [15.],
        [21.]])


Input data, Model Parameter (weight & bias), Output Data

Define the model

In [22]:
model = torch.nn.Linear(1, 1)  # Input size: 1, Output size: 1 , model= torch.nn.Linear(20, 30)

Train the model

In [23]:
learning_rate = 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [24]:
for epoch in range(1000):
    y_pred = model(X) # Forward pass

    loss = torch.mean((y_pred - y)**2) # Loss

    # Backward pass and optimization
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    # getting loss in every 100 epochs
    if epoch % 25 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

Epoch 0, Loss: 223.435546875
Epoch 25, Loss: 0.5303654670715332
Epoch 50, Loss: 0.46023643016815186
Epoch 75, Loss: 0.42052245140075684
Epoch 100, Loss: 0.38634130358695984
Epoch 125, Loss: 0.3569174110889435
Epoch 150, Loss: 0.3315899968147278
Epoch 175, Loss: 0.3097888231277466
Epoch 200, Loss: 0.2910234034061432
Epoch 225, Loss: 0.274870365858078
Epoch 250, Loss: 0.2609660029411316
Epoch 275, Loss: 0.2489975094795227
Epoch 300, Loss: 0.23869529366493225
Epoch 325, Loss: 0.22982710599899292
Epoch 350, Loss: 0.22219428420066833
Epoch 375, Loss: 0.2156236469745636
Epoch 400, Loss: 0.20996761322021484
Epoch 425, Loss: 0.20509964227676392
Epoch 450, Loss: 0.20090892910957336
Epoch 475, Loss: 0.1973017156124115
Epoch 500, Loss: 0.19419732689857483
Epoch 525, Loss: 0.19152480363845825
Epoch 550, Loss: 0.18922391533851624
Epoch 575, Loss: 0.1872437596321106
Epoch 600, Loss: 0.1855388730764389
Epoch 625, Loss: 0.18407177925109863
Epoch 650, Loss: 0.18280857801437378
Epoch 675, Loss: 0.181721

Model testing

In [25]:
X_test = torch.tensor([[5.0], [6.0], [10.0], [11.0]])
y_test_pred = model(X_test)

In [26]:
print(y_test_pred)

tensor([[25.4470],
        [30.3212],
        [49.8182],
        [54.6925]], grad_fn=<AddmmBackward0>)


In [27]:
print(y_test_pred)

tensor([[25.4470],
        [30.3212],
        [49.8182],
        [54.6925]], grad_fn=<AddmmBackward0>)
