<a href="https://colab.research.google.com/github/anishchapagain/Deep-Learning/blob/main/torch_tensor_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Scalar - Vector - Matrix & Tensor

In [ ]:
import torch

### Scalar

In [1]:
# scalar tensor

x = torch.tensor(5)
print(x)

tensor(5)


In [2]:
print(f"type : {x.dtype}") # data type
print(f"shape : {x.shape}") # shape
print(f"requires grad : {x.requires_grad}") # gradient tracking
print(f"item : {x.item()}") # convert to python int
print(f"nDim : {x.ndim}")


type : torch.int64
shape : torch.Size([])
requires grad : False
item : 5
nDim : 0


### Vector

In [3]:
v = torch.tensor([1,2,3])
print(v)

tensor([1, 2, 3])


In [5]:
print(f"type : {v.dtype}") # data type
print(f"shape : {v.shape}") # shape
print(f"requires grad : {v.requires_grad}") # gradient tracking
print(f"nDim : {v.ndim}")

type : torch.int64
shape : torch.Size([3])
requires grad : False
nDim : 1


### Matrix

In [6]:
# prompt: generate a matrix and reveal its major properties such as shape and individual elments

# ### Matrix
m = torch.tensor([[1,2,3],
                  [4,5,6]])
print(m)
print(f"type : {m.dtype}") # data type
print(f"shape : {m.shape}") # shape
print(f"requires grad : {m.requires_grad}") # gradient tracking
print(f"nDim : {m.ndim}")
print(m[0][0].item())
print(m[0][1].item())
print(m[0][2].item())


tensor([[1, 2, 3],
        [4, 5, 6]])
type : torch.int64
shape : torch.Size([2, 3])
requires grad : False
nDim : 2
1
2
3


### Tensor

In [7]:
# Generate a tensor
t = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Print the tensor
print("Tensor:", t)

# Print the shape of the tensor
print("Shape:", t.shape)

# Print the data type of the tensor
print("Data type:", t.dtype)

# Print the number of dimensions of the tensor
print("Number of dimensions:", t.ndim)

# Print the individual elements of the tensor
print("Individual elements:")
for i in range(t.shape[0]):
  for j in range(t.shape[1]):
    for k in range(t.shape[2]):
      print(f"t[{i}][{j}][{k}] = {t[i][j][k]}")


Tensor: tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
Shape: torch.Size([2, 2, 3])
Data type: torch.int64
Number of dimensions: 3
Individual elements:
t[0][0][0] = 1
t[0][0][1] = 2
t[0][0][2] = 3
t[0][1][0] = 4
t[0][1][1] = 5
t[0][1][2] = 6
t[1][0][0] = 7
t[1][0][1] = 8
t[1][0][2] = 9
t[1][1][0] = 10
t[1][1][1] = 11
t[1][1][2] = 12


In [8]:
t[0]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
t[1]

tensor([[ 7,  8,  9],
        [10, 11, 12]])