<a href="https://colab.research.google.com/github/anishchapagain/Deep-Learning/blob/main/torch_nn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch for Deep Learning Models

Linear Regression Model Training in PyTorch

In [2]:
import torch

Input Data: tensor

In [7]:
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
print(X)

tensor([[1.],
        [2.],
        [3.],
        [4.]])


Expected Output: y = 5x+1<br><b>Learning_weight:5, Learning_bias:1</b><br>
example: x=1, y=5*1+1 = 6

In [21]:
y = torch.tensor([[6.0], [11.0], [15.0], [21.0]]) # 21 = 5*4+1
print(y)

tensor([[ 6.],
        [11.],
        [15.],
        [21.]])


Input data, Model Parameter (weight & bias), Output Data

Define the model

In [28]:
# model = torch.nn.Linear(1, 1)  # Input size: 1, Output size: 1 , model= torch.nn.Linear(20, 30)

model = torch.nn.Linear(1, 10)

In [37]:
print(model)
print(f"Weight: {model.weight}")
print(f"Bias: {model.bias}")

Linear(in_features=1, out_features=10, bias=True)
Weight: Parameter containing:
tensor([[4.6240],
        [4.5613],
        [4.9965],
        [4.5242],
        [4.9280],
        [4.8455],
        [4.7953],
        [4.6109],
        [4.9931],
        [4.7188]], requires_grad=True)
Bias: Parameter containing:
tensor([1.8115, 1.9959, 0.7163, 2.1050, 0.9177, 1.1601, 1.3079, 1.8500, 0.7261,
        1.5327], requires_grad=True)


The weights and biases of the layer are initialized randomly and learned during the training process

In [35]:
models = torch.nn.Linear(2, 5)
print(models)
print(models.weight)
print(models.bias)


Linear(in_features=2, out_features=5, bias=True)
Parameter containing:
tensor([[-0.4470, -0.6388],
        [ 0.4378,  0.0953],
        [ 0.3476, -0.4315],
        [ 0.5936,  0.4835],
        [ 0.2164, -0.5710]], requires_grad=True)
Parameter containing:
tensor([ 0.5124, -0.4977, -0.0937,  0.1736,  0.1184], requires_grad=True)


Train the model

In [29]:
# The optimizer updates the model parameters based on the computed gradients
learning_rate = 0.01

# The model is trained using stochastic gradient descent (SGD) optimization
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

In [30]:
for epoch in range(1000):
    y_pred = model(X) # Forward pass

    loss = torch.mean((y_pred - y)**2) # mean squared error loss

    # Backward pass and optimization
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

    # getting loss in every 100 epochs
    if epoch % 25 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

Epoch 0, Loss: 209.60678100585938
Epoch 25, Loss: 90.4709701538086
Epoch 50, Loss: 39.14471435546875
Epoch 75, Loss: 17.031681060791016
Epoch 100, Loss: 7.504096984863281
Epoch 125, Loss: 3.39849591255188
Epoch 150, Loss: 1.6287692785263062
Epoch 175, Loss: 0.8653842806816101
Epoch 200, Loss: 0.5355549454689026
Epoch 225, Loss: 0.39252209663391113
Epoch 250, Loss: 0.329977810382843
Epoch 275, Loss: 0.30212217569351196
Epoch 300, Loss: 0.28922468423843384
Epoch 325, Loss: 0.2827847898006439
Epoch 350, Loss: 0.27914008498191833
Epoch 375, Loss: 0.27671223878860474
Epoch 400, Loss: 0.27482151985168457
Epoch 425, Loss: 0.27317479252815247
Epoch 450, Loss: 0.27164560556411743
Epoch 475, Loss: 0.27017900347709656
Epoch 500, Loss: 0.26875144243240356
Epoch 525, Loss: 0.2673526406288147
Epoch 550, Loss: 0.2659778594970703
Epoch 575, Loss: 0.2646248936653137
Epoch 600, Loss: 0.2632925808429718
Epoch 625, Loss: 0.2619803547859192
Epoch 650, Loss: 0.2606877088546753
Epoch 675, Loss: 0.25941431522

Model testing

In [31]:
X_test = torch.tensor([[5.0], [6.0], [10.0], [11.0]])
y_test_pred = model(X_test)

In [26]:
print(y_test_pred)

tensor([[25.4470],
        [30.3212],
        [49.8182],
        [54.6925]], grad_fn=<AddmmBackward0>)


In [32]:
print(y_test_pred) # model = torch.nn.Linear(1, 10)

tensor([[24.9314, 24.8023, 25.6988, 24.7258, 25.5576, 25.3878, 25.2843, 24.9045,
         25.6919, 25.1268],
        [29.5554, 29.3635, 30.6953, 29.2500, 30.4856, 30.2334, 30.0795, 29.5153,
         30.6850, 29.8456],
        [48.0513, 47.6086, 50.6813, 47.3466, 50.1975, 49.6155, 49.2606, 47.9589,
         50.6576, 48.7209],
        [52.6753, 52.1699, 55.6778, 51.8708, 55.1255, 54.4611, 54.0559, 52.5698,
         55.6507, 53.4398]], grad_fn=<AddmmBackward0>)
