<a href="https://colab.research.google.com/github/anishchapagain/Deep-Learning/blob/main/torch_tensor_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor: random data , range, dtype, numpy, math, image
[Doc](https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html)

In [1]:
import torch

Generate a random tensor data

In [2]:
z = torch.rand(3, 5)

print(z)

tensor([[0.7230, 0.7688, 0.4918, 0.4990, 0.9025],
        [0.6202, 0.2536, 0.5379, 0.9531, 0.3313],
        [0.6898, 0.8463, 0.8904, 0.7110, 0.3785]])


In [3]:
zn = torch.randn(3,5) # normal distribution
print(zn)


tensor([[ 0.3829,  0.9297, -0.4726,  0.0161, -0.5714],
        [-0.8528,  2.9368,  0.6552,  2.8415,  0.0941],
        [-1.6363, -1.5588,  0.4918,  1.3066, -0.5225]])


Few tensor properties

In [4]:
z.shape, z.dtype, z.ndim

(torch.Size([3, 5]), torch.float32, 2)

In [5]:
ra = torch.rand(2, 3, 5)
print(ra)

tensor([[[0.7740, 0.1816, 0.5400, 0.1608, 0.3197],
         [0.9013, 0.7961, 0.7959, 0.7603, 0.1371],
         [0.3806, 0.6917, 0.5006, 0.2040, 0.1884]],

        [[0.2268, 0.3978, 0.2645, 0.5984, 0.9665],
         [0.5106, 0.8138, 0.1545, 0.3528, 0.4028],
         [0.5008, 0.3433, 0.1817, 0.6557, 0.0820]]])


In [6]:
ra.shape, ra.dtype, ra.ndim

(torch.Size([2, 3, 5]), torch.float32, 3)

In [7]:
# Create random seed

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

In [ ]:
rand1 = torch.rand(3, 5)

torch.manual_seed(RANDOM_SEED)
rand2 = torch.rand(3, 5)

print(rand1)
print(rand2)
print(rand1==rand2)


tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411]])


In [ ]:
zero = torch.zeros(3, 5)
print(zero)

In [ ]:
ones = torch.ones(3, 5)
print(ones)

In [ ]:
# Get device

ones.device

## Range: Create a tensor of evenly spaced values from start to end, stepping by step


In [ ]:
start = 0
end = 10
step = 2

In [ ]:
range_tensor = torch.range(start, end, step)
print(range_tensor)

In [ ]:
result = torch.arange(start, end, step)
print(result)  # Output: tensor([0, 2, 4, 6, 8])

## DataTypes
### Memory issue

In [ ]:
dt = torch.tensor([1, 2, 3, 4])
print(dt.dtype)

In [ ]:
dt

In [ ]:
dtNone = torch.tensor([1, 2, 3, 4], dtype = None)
print(dtNone.dtype)

In [ ]:
dtNone

In [ ]:
dt32 = torch.tensor([1, 2, 3, 4], dtype = torch.float32)
print(dt32.dtype)

In [ ]:
dt32

In [ ]:
dt16 = torch.tensor([1, 2, 3, 4], dtype = torch.float16)
print(dt16.dtype)

In [ ]:
dt16

Multiply different 'dtype' tensor

In [ ]:
dt*dt16

In [ ]:
test = dt16*dt32
print(test)

In [ ]:
test.dtype, test.shape, test.ndim

**Numpy**

In [ ]:
import numpy as np

In [ ]:
ones = np.ones((3, 5))
print(ones)

In [ ]:
ones.dtype

### Convert ones to torch tensor **from_numpy** | **tensor.numpy**


In [ ]:
ones_tensor = torch.from_numpy(ones)
print(ones_tensor)

In [ ]:
ones_tensor.dtype

### Convert tensor to numpy


In [ ]:
numpy_array = ones_tensor.numpy()
print(numpy_array)

# Common properties
print("Tensor device:", ones_tensor.device)
print("Tensor shape:", ones_tensor.shape)
print("Numpy array shape:", numpy_array.shape)

print("Tensor dtype:", ones_tensor.dtype)
print("Numpy array dtype:", numpy_array.dtype)

In [ ]:
numpy_array = numpy_array+1
print(numpy_array)

## Math Operations

In [ ]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

### Tensor addition

In [ ]:
addition_result = tensor1 + tensor2

print("Addition Result:")
print(addition_result)

In [ ]:
addition_result = tensor1.add(tensor2) # tensor.add

print("\nAddition Result:")
print(addition_result)

In [ ]:
addition_result + 5

### Tensor subtraction

In [ ]:
subtraction_result = tensor1 - tensor2

print("\nSubtraction Result:")
print(subtraction_result)

In [ ]:
subtraction_result = tensor1.sub(tensor2) # tensor.sub

print("\nSubtraction Result:")
print(subtraction_result)

In [ ]:
subtraction_result-10

### Tensor multiplication (element-wise)


In [ ]:
multiplication_result = tensor1 * tensor2

print("\nElement-wise Multiplication Result:")
print(multiplication_result)

In [ ]:
multiplication_result = tensor1.mul(tensor2) # tensor.mul
print("\nElement-wise Multiplication Result:")
print(multiplication_result)

In [ ]:
multiplication_result*10

### Tensor division (element-wise)


In [ ]:
division_result = tensor1 / tensor2
print("\nElement-wise Division Result:")
print(division_result)

In [ ]:
division_result = tensor1.div(tensor2) # tensor.div
print("\nElement-wise Division Result:")
print(division_result)

In [ ]:
division_result/10

### Matrix multiplication

In [ ]:
tensor3 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor4 = torch.tensor([[7, 8], [9, 10], [11, 12]])
matrix_multiplication_result = torch.matmul(tensor3, tensor4) # matmul

# 1*7+2*9+3*11 = 58
# 1*8+2*10+3*12 = 64
# 4*7+5*9+6*11 = 139
# 4*8+5*10+6*12 = 154
print("\nMatrix Multiplication Result:")
print(matrix_multiplication_result)

In [ ]:
# tensor.matmul or tensor3 @ tensor4 or torch.mm

matrix_multiplication_result = tensor3.matmul(tensor4)
print("\nMatrix Multiplication Result:")
print(matrix_multiplication_result)

In [ ]:
matrix_multiplication_result.shape, matrix_multiplication_result.ndim

#### <u>**inner dimension** of two matrix should be same, resulting matrix will be of **outer demension**</u>

### Matrix transpose (**tensor.T**)


In [ ]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
transposed_tensor = tensor.T  # or torch.transpose(tensor, 0, 1)

print("\nOriginal Tensor:")
print(tensor)
print("\nTransposed Tensor:")
print(transposed_tensor)

### Example to illustrate the need for transpose in matrix multiplication

In [ ]:

# Let's say we have two matrices:
matrix1 = torch.tensor([[1, 2],
                       [3, 4]])
matrix2 = torch.tensor([[5, 6],
                       [7, 8]])

# If we try to multiply them directly (without transpose):
try:
  result = torch.matmul(matrix1, matrix2)
  print(result)
except RuntimeError as e:
  print("\nError:", e)

# This will throw an error because the inner dimensions don't match for matrix multiplication.
# matrix1 (2x2) and matrix2 (2x2) -> inner dimensions are both 2.

### To perform matrix multiplication, we need to transpose one of the matrices so that the inner dimensions match. Let's transpose matrix2:

In [ ]:
matrix2

In [ ]:
matrix2_transposed = matrix2.T
matrix2_transposed

In [ ]:
# Now, the multiplication will work:
result = torch.matmul(matrix1, matrix2_transposed)

print("\nResult after transposing matrix2:")
print(result)

# Explanation:
# - Matrix multiplication requires the number of columns in the first matrix
#   to match the number of rows in the second matrix.

# - By transposing matrix2, we swapped its rows and columns, making the inner dimensions compatible.
# - This allows us to perform the multiplication and obtain the correct result.


## Aggregation

In [ ]:
tensor1

In [ ]:
tensor2 = torch.tensor([[5,6,7],[8,9,10]])
tensor2

### Sum of all elements in a tensor

In [ ]:
sum_one = torch.sum(tensor1)  # or tensor1.sum()
print(f"Sum of all elements in tensor1: {sum_one}")
sum_two = torch.sum(tensor2)
print(f"Sum of all elements in tensor2: {sum_two}")

### Min of all elements in a tensor

In [ ]:
min_one = torch.min(tensor1) # tensor1.min()
print(f"Minimum of all elements in tensor1: {min_one}")
min_two = torch.min(tensor2)
print(f"Minimum of all elements in tensor2: {min_two}")

In [ ]:
# tensor1.argmin() # provides the index
# tensor1.argmax()

### Max of all elements in a tensor

In [ ]:
max_one = torch.max(tensor1) # tensor1.max()
print(f"Maximum of all elements in tensor1: {max_one}")
max_two = torch.max(tensor2)
print(f"Maximum of all elements in tensor2: {max_two}")

### Mean of all elements in a tensor

In [ ]:
mean_one = torch.mean(tensor1.float())  # or tensor1.float().mean()
print(f"Mean of all elements in tensor1: {mean_one}")

mean_two = torch.mean(tensor2.float())
print(f"Mean of all elements in tensor2: {mean_two}")

In [ ]:
# tensor1.mean()
# RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

# change the datatype and then calculate the mean

In [ ]:
tensor1.float().mean()

In [ ]:
torch.mean(tensor1.type(torch.float32))

# Generating a random tensor for an image (example: 3 channels, 224x224 pixels)

In [ ]:
image_tensor = torch.rand(3, 224, 224) # RGB; color channel, height*width

In [ ]:
print("Shape of the tensor: ", image_tensor.shape)
print("Datatype of the tensor: ", image_tensor.dtype)
print("Number of dimensions in the tensor: ", image_tensor.ndim)
print("Device tensor is stored on: ", image_tensor.device)

Shape of the tensor:  torch.Size([3, 224, 224])
Datatype of the tensor:  torch.float32
Number of dimensions in the tensor:  3
Device tensor is stored on:  cpu
