<a href="https://colab.research.google.com/github/anishchapagain/Deep-Learning/blob/main/torch_linear_reg_II_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch for Deep Learning Models

Linear Regression Model Training in PyTorch

In [ ]:
import torch

Input Data: tensor

In [ ]:
X = torch.tensor([[1.0], [2.0], [3.0], [4.0]])
print(X)

tensor([[1.],
        [2.],
        [3.],
        [4.]])


Expected Output: y = 5x+1<br><b>Learning_weight:5, Learning_bias:1</b><br>
example: x=1, y=5*1+1 = 6

In [ ]:
y = torch.tensor([[6.0], [11.0], [15.0], [21.0]]) # 21 = 5*4+1
print(y)

tensor([[ 6.],
        [11.],
        [15.],
        [21.]])


In [ ]:
len(X), len(y)

(4, 4)

Input data, Model Parameter (weight & bias), Output Data

Define the model

In [ ]:
# model = torch.nn.Linear(1, 1)  # Input size: 1, Output size: 1 , model= torch.nn.Linear(20, 30)

model = torch.nn.Linear(1, 1)
print(model)

Linear(in_features=1, out_features=1, bias=True)


In [ ]:
model.state_dict()

OrderedDict([('weight', tensor([[-0.0690]])), ('bias', tensor([-0.8796]))])

In [ ]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.0690]], requires_grad=True),
 Parameter containing:
 tensor([-0.8796], requires_grad=True)]

In [ ]:
print(f"Weight: {model.weight}")
print(f"Bias: {model.bias}")

Weight: Parameter containing:
tensor([[-0.0690]], requires_grad=True)
Bias: Parameter containing:
tensor([-0.8796], requires_grad=True)


The weights and biases of the layer are initialized randomly and learned during the training process

In [ ]:
models = torch.nn.Linear(2, 5)
print(models)
print(models.weight)
print(models.bias)


Linear(in_features=2, out_features=5, bias=True)
Parameter containing:
tensor([[-0.4470, -0.6388],
        [ 0.4378,  0.0953],
        [ 0.3476, -0.4315],
        [ 0.5936,  0.4835],
        [ 0.2164, -0.5710]], requires_grad=True)
Parameter containing:
tensor([ 0.5124, -0.4977, -0.0937,  0.1736,  0.1184], requires_grad=True)


Train the model

In [ ]:
# The optimizer updates the model parameters based on the computed gradients
learning_rate = 0.01
loss_fn = torch.nn.L1Loss()

# The model is trained using stochastic gradient descent (SGD) optimization
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate) # Adam

In [ ]:
model.state_dict()

OrderedDict([('weight', tensor([[-0.0690]])), ('bias', tensor([-0.8796]))])

In [ ]:
model.parameters()

<generator object Module.parameters at 0x790424ad0580>

In [ ]:
# training loop

for epoch in range(50):
    y_pred = model(X) # Forward pass

    # loss = loss_fn(y_pred, y_train) 
    loss = torch.mean((y_pred - y)**2) # mean squared error loss calculation
    print(f"Loss: {loss}")

    # Backward pass and optimization - I
    optimizer.zero_grad() # optimizer
    loss.backward() # back propagation on loss
    optimizer.step() # optimizer ->SGD

    print(model.state_dict())

    # Testing
    """
    model.eval()
    with torch.inference_mode():
        test_pred = model(X_test)
        test_loss = loss_fn(test_pred, y_test)
    """
    # Print the loss every 5 epochs
    if epoch % 25 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

Loss: 0.1776466816663742
OrderedDict([('weight', tensor([[4.9427]])), ('bias', tensor([0.8745]))])
Epoch 0, Loss: 0.1776466816663742
Loss: 0.17763108015060425
OrderedDict([('weight', tensor([[4.9426]])), ('bias', tensor([0.8749]))])
Loss: 0.17761534452438354
OrderedDict([('weight', tensor([[4.9424]])), ('bias', tensor([0.8752]))])
Loss: 0.1775994896888733
OrderedDict([('weight', tensor([[4.9423]])), ('bias', tensor([0.8756]))])
Loss: 0.1775839924812317
OrderedDict([('weight', tensor([[4.9422]])), ('bias', tensor([0.8760]))])
Loss: 0.1775687336921692
OrderedDict([('weight', tensor([[4.9421]])), ('bias', tensor([0.8764]))])
Loss: 0.17755332589149475
OrderedDict([('weight', tensor([[4.9419]])), ('bias', tensor([0.8767]))])
Loss: 0.17753808200359344
OrderedDict([('weight', tensor([[4.9418]])), ('bias', tensor([0.8771]))])
Loss: 0.17752256989479065
OrderedDict([('weight', tensor([[4.9417]])), ('bias', tensor([0.8775]))])
Loss: 0.1775076538324356
OrderedDict([('weight', tensor([[4.9416]])), 

Model testing

In [ ]:
X_test = torch.tensor([[5.0], [6.0], [10.0], [11.0]])
y_test_pred = model(X_test)

In [ ]:
print(y_test_pred)

tensor([[25.5759],
        [30.5128],
        [50.2602],
        [55.1971]], grad_fn=<AddmmBackward0>)


In [ ]:
print(y_test_pred) # model = torch.nn.Linear(1, 10)

tensor([[25.5882],
        [30.5310],
        [50.3023],
        [55.2451]], grad_fn=<AddmmBackward0>)


In [ ]:
model.state_dict()

OrderedDict([('weight', tensor([[4.9369]])), ('bias', tensor([0.8916]))])