# Logistic Regression

## Logistic regression is defined as a supervised machine learning algorithm that accomplishes binary classification tasks by predicting the probability of an outcome, event, or observation. 

### https://machinelearningmastery.com/logistic-regression-tutorial-for-machine-learning/

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(filepath_or_buffer='../dataset/credit_card_default.csv')

In [3]:
df.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [4]:
df # .columns[:5]

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  \
0          1      20000    2          2         1   24      2      2     -1   
1          2     120000    2          2         2   26     -1      2      0   
2          3      90000    2          2         2   34      0      0      0   
3          4      50000    2          2         1   37      0      0      0   
4          5      50000    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0         -1  ...          0          0          0         0       689   
1          0  ...       3272       3455       3261         0      1000   
2          0  ...      14331      14948      15549      1518      1500   
3          0  ...      28314      28959      29547      2000      2019   
4          0  ...      20940      19146      19131      2000     36681   
...      ...  ...        ...        ...        ...       ...       ...   
29995      0  ...      88004      31237      15980      8500     20000   
29996     -1  ...       8979       5190          0      1837      3526   
29997     -1  ...      20878      20582      19357         0         0   
29998      0  ...      52774      11855      48944     85900      3409   
29999      0  ...      36535      32428      15313      2078      1800   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0             0         0         0         0                           1  
1          1000      1000         0      2000                           1  
2          1000      1000      1000      5000                           0  
3          1200      1100      1069      1000                           0  
4         10000      9000       689       679                           0  
...         ...       ...       ...       ...                         ...  
29995      5003      3047      5000      1000                           0  
29996      8998       129         0         0                           0  
29997     22000      4200      2000      3100                           1  
29998      1178      1926     52964      1804                           1  
29999      1430      1000      1000      1000                           1  

[30000 rows x 25 columns]

In [5]:
df.describe()

ID       LIMIT_BAL           SEX     EDUCATION      MARRIAGE  \
count  30000.000000    30000.000000  30000.000000  30000.000000  30000.000000   
mean   15000.500000   167484.322667      1.603733      1.853133      1.553667   
std     8660.398374   129747.661567      0.489129      0.790349      0.518326   
min        1.000000    10000.000000      1.000000      0.000000      1.000000   
25%     7500.750000    50000.000000      1.000000      1.000000      1.000000   
50%    15000.500000   140000.000000      2.000000      2.000000      2.000000   
75%    22500.250000   240000.000000      2.000000      2.000000      2.000000   
max    30000.000000  1000000.000000      2.000000      6.000000      3.000000   

                AGE         PAY_1         PAY_2         PAY_3         PAY_4  \
count  30000.000000  30000.000000  30000.000000  30000.000000  30000.000000   
mean      35.485500     -0.016700     -0.133767     -0.166200     -0.220667   
std        9.217904      1.123802      1.197186      1.196868      1.169139   
min       21.000000     -2.000000     -2.000000     -2.000000     -2.000000   
25%       28.000000     -1.000000     -1.000000     -1.000000     -1.000000   
50%       34.000000      0.000000      0.000000      0.000000      0.000000   
75%       41.000000      0.000000      0.000000      0.000000      0.000000   
max       79.000000      8.000000      8.000000      8.000000      8.000000   

       ...      BILL_AMT4      BILL_AMT5      BILL_AMT6       PAY_AMT1  \
count  ...   30000.000000   30000.000000   30000.000000   30000.000000   
mean   ...   43262.948967   40311.400967   38871.760400    5663.580500   
std    ...   64332.856134   60797.155770   59554.107537   16563.280354   
min    ... -170000.000000  -81334.000000 -339603.000000       0.000000   
25%    ...    2326.750000    1763.000000    1256.000000    1000.000000   
50%    ...   19052.000000   18104.500000   17071.000000    2100.000000   
75%    ...   54506.000000   50190.500000   49198.250000    5006.000000   
max    ...  891586.000000  927171.000000  961664.000000  873552.000000   

           PAY_AMT2      PAY_AMT3       PAY_AMT4       PAY_AMT5  \
count  3.000000e+04   30000.00000   30000.000000   30000.000000   
mean   5.921163e+03    5225.68150    4826.076867    4799.387633   
std    2.304087e+04   17606.96147   15666.159744   15278.305679   
min    0.000000e+00       0.00000       0.000000       0.000000   
25%    8.330000e+02     390.00000     296.000000     252.500000   
50%    2.009000e+03    1800.00000    1500.000000    1500.000000   
75%    5.000000e+03    4505.00000    4013.250000    4031.500000   
max    1.684259e+06  896040.00000  621000.000000  426529.000000   

            PAY_AMT6  default payment next month  
count   30000.000000                30000.000000  
mean     5215.502567                    0.221200  
std     17777.465775                    0.415062  
min         0.000000                    0.000000  
25%       117.750000                    0.000000  
50%      1500.000000                    0.000000  
75%      4000.000000                    0.000000  
max    528666.000000                    1.000000  

[8 rows x 25 columns]

In [6]:
# Clean and Renmae columns

df.rename(columns=lambda x: x.lower(), inplace=True)
df = df[['pay_amt1','age','default payment next month']]

df.rename(columns={'pay_amt1':'amount'}, inplace=True)

# next_payment: yes|no => 1|0
df.rename(columns={'default payment next month':'next_payment'}, inplace=True)

C:\Users\PETERCHAPAGAIN\AppData\Local\Temp\ipykernel_6760\3537591757.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'pay_amt1':'amount'}, inplace=True)
C:\Users\PETERCHAPAGAIN\AppData\Local\Temp\ipykernel_6760\3537591757.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'default payment next month':'next_payment'}, inplace=True)


In [7]:
df['amount'].describe()

count     30000.000000
mean       5663.580500
std       16563.280354
min           0.000000
25%        1000.000000
50%        2100.000000
75%        5006.000000
max      873552.000000
Name: amount, dtype: float64

In [8]:
# df['amount'] = df['amount']/1000

In [9]:
df.head()

amount  age  next_payment
0       0   24             1
1       0   26             1
2    1518   34             0
3    2000   37             0
4    2000   57             0

In [10]:
df[df['amount']==0.0]

amount  age  next_payment
0           0   24             1
1           0   26             1
9           0   35             0
15          0   23             0
18          0   49             0
...       ...  ...           ...
29979       0   32             0
29985       0   30             0
29986       0   35             0
29991       0   34             1
29997       0   37             1

[5249 rows x 3 columns]

In [75]:
df.next_payment[0:1000:100]

2       0
127     1
246     0
366     0
487     0
606     0
734     0
856     1
975     0
1103    0
Name: next_payment, dtype: int64

In [11]:
# remove amount with 0

df = df[df['amount'] != 0]

In [12]:
df[df['amount']==0.0].count()

amount          0
age             0
next_payment    0
dtype: int64

In [13]:
df[df['age']<44].value_counts()

amount  age  next_payment
2000    29   0               68
        25   0               68
        23   0               64
        26   0               59
        24   0               58
                             ..
2036    40   0                1
2037    34   0                1
        36   0                1
        40   0                1
873552  42   0                1
Name: count, Length: 13601, dtype: int64

In [14]:
df[df['age']==29]['amount'].sum() # random check

9341176

In [15]:
df.groupby('age').mean().head(10)

amount  next_payment
age                           
21   2253.983871      0.161290
22   2916.353846      0.270330
23   3822.705957      0.230672
24   4188.187027      0.240000
25   5532.905941      0.228713
26   5727.390848      0.172545
27   6301.765905      0.185155
28   7406.173208      0.174915
29   7114.376238      0.162224
30   7211.638063      0.169924

In [16]:
df.index

Index([    2,     3,     4,     5,     6,     7,     8,    10,    11,    12,
       ...
       29988, 29989, 29990, 29992, 29993, 29994, 29995, 29996, 29998, 29999],
      dtype='int64', length=24751)

In [38]:
df['amount'] = df['amount']/1000

In [18]:
from sklearn.linear_model import LogisticRegression

In [39]:
X = df[['amount','age']] # input value X1, X2 (Independent Variable)
y = df['next_payment'] # binary classification (Dependent Variable)

In [40]:
model = LogisticRegression(max_iter=500, random_state=42) # Try: random_state, solver, multi_class

model.fit(X, y)

LogisticRegression(max_iter=500, random_state=42)

In [41]:
model.intercept_, model.coef_, model.score(X,y)

(array([-1.41743901]), array([[-0.02063138,  0.00269902]]), 0.8081289644862834)

In [42]:
model.predict(X[0:10])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [43]:
model.predict_proba(X[10:20])

array([[0.80257854, 0.19742146],
       [0.8023523 , 0.1976477 ],
       [0.80513187, 0.19486813],
       [0.81740841, 0.18259159],
       [0.79803716, 0.20196284],
       [0.7889648 , 0.2110352 ],
       [0.8003801 , 0.1996199 ],
       [0.84687581, 0.15312419],
       [0.81368529, 0.18631471],
       [0.80155909, 0.19844091]])

In [44]:
model.predict_log_proba(X[20:80:5])

array([[-0.22778711, -1.59107635],
       [-0.22171869, -1.61515777],
       [-0.22260148, -1.61160915],
       [-0.22260148, -1.61160915],
       [-0.15649399, -1.93196442],
       [-0.22598288, -1.59816055],
       [-0.22578756, -1.59893122],
       [-0.22225482, -1.61300075],
       [-0.24058326, -1.54257015],
       [-0.19789535, -1.71733334],
       [-0.11036955, -2.25859828],
       [-0.22087685, -1.61855644]])

In [28]:
from sklearn import metrics

In [45]:
metrics.accuracy_score(y[10:50:5], model.predict(X[10:50:5]))

0.75

In [46]:
metrics.confusion_matrix(y[10:50:5], model.predict(X[10:50:5]))

array([[6, 0],
       [2, 0]], dtype=int64)

In [32]:
import numpy as np

In [47]:
def calculate(index, amount, age):
    # prediction = 1 / (1 + e^(-(b0 + b1*x1 + b2*x2)))
    
    b = (model.intercept_[0] + model.coef_[0][0]*amount + model.coef_[0][1]*age)
    
    predict = 1/(1 + np.exp(-b))
    
    crisp = 0 if predict < 0.5 else 1
    
    yes = 'Yes' if crisp > 0.5 else ''
        
    return f"{index} - Amount: {amount*1000}, Age: {age}, Prob: {predict} - Crisp: {crisp} {yes}"

In [34]:
import random

In [48]:
# Calculate probability

for i in list(range(1,25)):
    print(calculate(i, amount=random.randrange(1, 6), age=random.randrange(27,42)))

1 - Amount: 4000, Age: 38, Prob: 0.19822872571967576 - Crisp: 0 -- 
2 - Amount: 1000, Age: 28, Prob: 0.2038346337278521 - Crisp: 0 -- 
3 - Amount: 3000, Age: 33, Prob: 0.1993653684429153 - Crisp: 0 -- 
4 - Amount: 3000, Age: 41, Prob: 0.20283426528530363 - Crisp: 0 -- 
5 - Amount: 3000, Age: 30, Prob: 0.19807607129284793 - Crisp: 0 -- 
6 - Amount: 5000, Age: 32, Prob: 0.19244087207798016 - Crisp: 0 -- 
7 - Amount: 4000, Age: 39, Prob: 0.19865804128206213 - Crisp: 0 -- 
8 - Amount: 4000, Age: 33, Prob: 0.1960926265002966 - Crisp: 0 -- 
9 - Amount: 2000, Age: 40, Prob: 0.20574925029267546 - Crisp: 0 -- 
10 - Amount: 2000, Age: 35, Prob: 0.20355268491470566 - Crisp: 0 -- 
11 - Amount: 3000, Age: 29, Prob: 0.1976477032108562 - Crisp: 0 -- 
12 - Amount: 4000, Age: 33, Prob: 0.1960926265002966 - Crisp: 0 -- 
13 - Amount: 1000, Age: 38, Prob: 0.2082497905552438 - Crisp: 0 -- 
14 - Amount: 2000, Age: 33, Prob: 0.20267896073208744 - Crisp: 0 -- 
15 - Amount: 2000, Age: 36, Prob: 0.2039905972635

In [49]:
for index,row in df.iterrows():
    print(calculate(index, row.amount, row.age))

2 - Amount: 1518.0, Age: 34.0, Prob: 0.2047298101322071 - Crisp: 0 -- 
3 - Amount: 2000.0, Age: 37.0, Prob: 0.20442920989852975 - Crisp: 0 -- 
4 - Amount: 2000.0, Age: 57.0, Prob: 0.2133486094945054 - Crisp: 0 -- 
5 - Amount: 2500.0, Age: 37.0, Prob: 0.20275660192065875 - Crisp: 0 -- 
6 - Amount: 55000.0, Age: 29.0, Prob: 0.07770872002808939 - Crisp: 0 -- 
7 - Amount: 380.0, Age: 23.0, Prob: 0.20372046711120204 - Crisp: 0 -- 
8 - Amount: 3329.0, Age: 28.0, Prob: 0.19614758006977256 - Crisp: 0 -- 
10 - Amount: 2306.0, Age: 34.0, Prob: 0.20209553533133034 - Crisp: 0 -- 
11 - Amount: 21818.0, Age: 51.0, Prob: 0.15059722531668596 - Crisp: 0 -- 
12 - Amount: 1000.0, Age: 41.0, Prob: 0.20958800198477123 - Crisp: 0 -- 
13 - Amount: 3200.0, Age: 30.0, Prob: 0.19742146190997928 - Crisp: 0 -- 
14 - Amount: 3000.0, Age: 29.0, Prob: 0.1976477032108562 - Crisp: 0 -- 
16 - Amount: 3200.0, Age: 24.0, Prob: 0.19486813271163547 - Crisp: 0 -- 
17 - Amount: 10358.0, Age: 49.0, Prob: 0.1825915879683256 - 

## Using sklearn train-test-split

In [51]:
from sklearn.model_selection import train_test_split

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=20)

In [60]:
len(X_train), len(y_train), len(X)

(19800, 19800, 24751)

In [62]:
skModel = LogisticRegression(max_iter=500)
skModel.fit(X_train, y_train)

LogisticRegression(max_iter=500)

### Score & Predict

In [63]:
skModel.score(X_train, y_train), model.score(X,y)

(0.8083333333333333, 0.8081289644862834)

In [64]:
skModel.predict(X_test), model.predict(X)

(array([0, 0, 0, ..., 0, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 0, 0, 0], dtype=int64))

### Classification Report

In [66]:
from sklearn.metrics import classification_report

In [69]:
print(classification_report(y_test, skModel.predict(X_test)))

              precision    recall  f1-score   support

           0       0.81      1.00      0.89      3997
           1       0.00      0.00      0.00       954

    accuracy                           0.81      4951
   macro avg       0.40      0.50      0.45      4951
weighted avg       0.65      0.81      0.72      4951



c:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [70]:
print(classification_report(y, model.predict(X)))

              precision    recall  f1-score   support

           0       0.81      1.00      0.89     20002
           1       0.00      0.00      0.00      4749

    accuracy                           0.81     24751
   macro avg       0.40      0.50      0.45     24751
weighted avg       0.65      0.81      0.72     24751



c:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
